# Generated by Django 4.2.1 on 2023-05-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_slug_en_category_slug_ru_category_slug_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_uz',
        ),
    ]
