# Generated by Django 4.2.1 on 2023-05-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_slug_en_remove_category_slug_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
