# Generated by Django 4.2.1 on 2023-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_name_en_category_name_ru_category_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
