# Generated by Django 4.2.1 on 2023-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
    ]
