# Generated by Django 4.2.1 on 2023-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_blog_image_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimage',
            name='delete_image',
            field=models.BooleanField(default=False),
        ),
    ]
