# Generated by Django 4.2.1 on 2023-05-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multipleimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
