# Generated by Django 4.2.1 on 2023-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_multipleimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=255, verbose_name='Название конференции/статьи')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('min_volume', models.CharField(blank=True, max_length=255, null=True, verbose_name='Минимальный объем статьи')),
                ('font', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шрифт')),
                ('font_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер шрифта')),
                ('line_spacing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Междустрочный интервал')),
                ('margins', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поля')),
                ('journal_languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Языки журнала')),
                ('structure_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Структура статьи')),
                ('header_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО автора')),
                ('student_info', models.CharField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город')),
                ('annotation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аннотация')),
                ('supervisor_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель')),
                ('article_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке')),
                ('bibliography', models.CharField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке')),
            ],
            options={
                'verbose_name': 'Требование статьи',
                'verbose_name_plural': 'Требования статей',
            },
        ),
    ]
