# Generated by Django 4.2.1 on 2023-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annotation_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='article',
            name='annotation_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='article',
            name='annotation_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AddField(
            model_name='article',
            name='bibliography_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='bibliography_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='bibliography_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_size_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер шрифта'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_size_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер шрифта'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_size_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер шрифта'),
        ),
        migrations.AddField(
            model_name='article',
            name='font_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='article',
            name='header_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='header_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='header_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_languages_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Языки журнала'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_languages_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Языки журнала'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_languages_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Языки журнала'),
        ),
        migrations.AddField(
            model_name='article',
            name='line_spacing_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Междустрочный интервал'),
        ),
        migrations.AddField(
            model_name='article',
            name='line_spacing_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Междустрочный интервал'),
        ),
        migrations.AddField(
            model_name='article',
            name='line_spacing_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Междустрочный интервал'),
        ),
        migrations.AddField(
            model_name='article',
            name='margins_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поля'),
        ),
        migrations.AddField(
            model_name='article',
            name='margins_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поля'),
        ),
        migrations.AddField(
            model_name='article',
            name='margins_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поля'),
        ),
        migrations.AddField(
            model_name='article',
            name='min_volume_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Минимальный объем статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='min_volume_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Минимальный объем статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='min_volume_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Минимальный объем статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_article_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название конференции/статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_article_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название конференции/статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_article_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название конференции/статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='structure_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Структура статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='structure_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Структура статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='structure_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Структура статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='student_info_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AddField(
            model_name='article',
            name='student_info_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AddField(
            model_name='article',
            name='student_info_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_info_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_info_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_info_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
    ]
