# Generated by Django 4.2.1 on 2023-06-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_article_annotation_en_article_annotation_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='structure_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='structure_text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='structure_text_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='structure_text_uz',
        ),
    ]
