# Generated by Django 4.2.1 on 2023-06-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_article_structure_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_uz',
        ),
    ]
