# Generated by Django 4.2.1 on 2023-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_article_slug_remove_article_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='supervisor_info',
        ),
        migrations.RemoveField(
            model_name='article',
            name='supervisor_info_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='supervisor_info_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='supervisor_info_uz',
        ),
        migrations.AddField(
            model_name='article',
            name='key_words',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='key_words_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='key_words_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='key_words_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
    ]
