# Generated by Django 4.2.1 on 2023-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_article_supervisor_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст статьи/Текст статьи на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibliography',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibliography_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibliography_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibliography_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Список литературы/Список литературы на английском языке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_title_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_title_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_title_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок/название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_article',
            field=models.CharField(max_length=255, verbose_name='Требования к оформлению статьи...(в научном...    )'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_article_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Требования к оформлению статьи...(в научном...    )'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_article_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Требования к оформлению статьи...(в научном...    )'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_article_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Требования к оформлению статьи...(в научном...    )'),
        ),
        migrations.AlterField(
            model_name='article',
            name='student_info',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AlterField(
            model_name='article',
            name='student_info_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AlterField(
            model_name='article',
            name='student_info_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
        migrations.AlterField(
            model_name='article',
            name='student_info_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=' Ученое звание, Студент, магистрант или аспирант, вуз, страна, город'),
        ),
    ]
