# Generated by Django 4.2.1 on 2023-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_article_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supervisor',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='supervisor_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Научный руководитель'),
        ),
    ]
